### ISSUE TITLE
Ruler not hiding after playback stop

### ISSUE THREAD

**Issue by spvkgn** [cboxdoerfer/ddb_waveform_seekbar#13]
When playback stop the ruler still displayed:
![ruler1](https://cloud.githubusercontent.com/assets/4147135/12871480/354b879e-cd9f-11e5-850e-3becedfe41e4.png)

Also if after hide/unhide DB to tray a black line stays on:
![ruler2](https://cloud.githubusercontent.com/assets/4147135/12871485/7c2a60f4-cd9f-11e5-9bd2-2470962a42cc.png)

It would be useful if this issue could be fixed.

**Comment by cboxdoerfer** [comment]
Thx for reporting. Fixed.

**Comment by spvkgn** [comment]
@cboxdoerfer this also happens if playback ended (end of playlist) and deadbeef restored from tray:

![ddb](https://cloud.githubusercontent.com/assets/4147135/15288172/53b1aad6-1b8a-11e6-8d07-c1ba09b61f6e.png)
