### ISSUE TITLE
customize the seekbar's height?

### ISSUE THREAD

**Issue by kragol** [cboxdoerfer/ddb_waveform_seekbar#15]
The height of the seekbar is very large on my 1080p monitor (at least in my opinion) and there does not seem to be any way of configuring it. I guess it might look OK for 2 channels but with the "downmix to mono" setting, it just looks absurdly large.

I modified the code at line 1448 in waveform.c from

```
gtk_widget_set_size_request (w->base.widget, 300, 96);
```

to

```
gtk_widget_set_size_request (w->base.widget, 300, 48);
```

and it seems to solve the problem for me.

Could there be a setting to choose the height in a configuration dialog? Or is there something that might break if the height is not 96? Or not constant?

Cheers.

**Comment by cboxdoerfer** [comment]
Just add a splitter to your deadbeef layout, put the waveform inside, resize it to the height you like and lock the height.

If that doesn't tell you much, i.e. your not familiar with deadbeefs design mode, just ask and I'll give you a more detailed explanation.

**Comment by kragol** [comment]
OK I didn't think of that one trick. Thanks.

**Comment by slashdevslashurandom** [comment]
The trick works well, but it seems like 96 is still the _minimal_ height for the seekbar, so I'll need to make the similar modification myself.
