### ISSUE TITLE
Waveform doesn't work with Opus in Pipewire

### ISSUE THREAD

**Issue by Schweber** [cboxdoerfer/ddb_waveform_seekbar#29]
The Plugin worked for me while using Pulseaudio, DeaDBeeF 1.8.8 and plugin version 0.5 with Kernel 5.14.10. 

Since switching to Pipewire, the Plugin only works for my .m4a files, not for my .opus files. With opus files, the waveform is clear and only the bar indicating the present position is shown.

Could this please be fixed? I like the waveform seekbar very much.

**Comment by cboxdoerfer** [comment]
I can't reproduce this issue. Can you provide a link to an opus file which causes the bug? Can be a simple test snippet.

**Comment by Schweber** [comment]
Please see the attached files. They are representative of all my .m4a and .opus files. Waveform creation works with .m4a files but not with .opus files.

The app "Quod Libet" also has a Waveform Seekbar and also fails since switching to Pipewire. I therefore see a connection to Pipewire with this issue.

[Files.zip](https://github.com/cboxdoerfer/ddb_waveform_seekbar/files/7448298/Files.zip)

**Comment by maklamj** [comment]
Try renaming  .opus to .ogg.

**Comment by Schweber** [comment]
If i rename to .ogg, DeaDBeeF says "ERROR: could not load:" and doesn't play the file.

In the log it also says "plugin Waveform Seekbar failed to connect to dependencies, deactivated."

However, as mentioned, the plugin still works with my  .m4a files, even though it says "deactivated" in the log.







31. Okt. 2021, 15:41 von ***@***.***:

**Comment by RiedleroD** [comment]
must be a config issue with your pipewire instance, since I can't reproduce either (and I'm using both opus and pipewire as daily drivers)
