### ISSUE TITLE
Progressbar color: opacity has no effect

### ISSUE THREAD

**Issue by Soukyuu** [cboxdoerfer/ddb_waveform_seekbar#7]
Changing opacity of the progress bar color has no effect, the color is always displayed as opaque.

I wanted to be able to make the bar completely invisible and only shade the waveform, but that doesn't seem to be possible because those colors are linked (and opacity doesn't work)

**Comment by cboxdoerfer** [comment]
As far as I understand you want the cursor - the small bar that indicates the playack postion - to be invisible? You can do so in the second settings dialog.

Edit -> Preferences -> Plugins -> Waveform Seekbar -> Configure -> Cursor width = 0

Hope that helps :)

**Comment by Soukyuu** [comment]
Yes, that works, thanks. 

Is there any reason why the settings are split between the plugin settings and the component right-click dialogue? It's a bit inconvenient having to jump between the two dialogues to fine-tune all settings. (Same is valid for the musical spectrum component btw).

**Comment by cboxdoerfer** [comment]
There are a couple of reasons, one being that I like to put features that can break the user experience if the user doesn't know what he is doing in the second dialog, e.g. the number of samples in the waveform plugin. So in this way I consider the second dialog as an "advanced settings" version. Then there are a couple of settings I haven't had time to move to the major settings dialog or I'm not sure yet how the UI should look like. And last there are some settings I'm not sure if I keep them, so I don't want to put them in a prominent position if they maybe are going to vanish or get overhauled completely. For example that's the case with the gaps handling in the spectrum plugin.

But for the most part it's the lack of time to port them to the major dialog and think of a usable and nice UI to hold all these settings.
